version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt_node_backend
    ports:
      - "5000:5000" # host:container
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
